application: wfesynchroshare
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static
  
- url: /upload
  script: upload.py

- url: /sites
  script: upload.py

- url: /.*
  script: main.py
  

  
