application: wfesynchrosharer
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /upload
  script: upload.app

- url: /checkurl
  script: upload.app

- url: /uploadimg
  script: upload.app

- url: /login
  script: login.app

- url: /.*
  script: main.app

libraries:
- name: lxml
  version: latest
